format = """
$directory\
[](fg:#88C0D0 bg:#1d2230)\
$git_branch\
[](fg:#1d2230)\
$jobs\
\n$character
"""

add_newline = true

[directory]
style = "fg:#2E3440 bg:#88C0D0 bold"
format = "[ $path ]($style)"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#1d2230"
format = '[ $symbol $branch ]($style)'

[jobs]
symbol = "+"
number_threshold = 1

[character]
vimcmd_symbol = '[V](bold green) '
